### ISSUE TITLE
(FOR THIS WEEK) Layout changes to the FAQ list item

### ISSUE THREAD

**Issue by mcrbsc** [miranda-company/bsc-dust-regional-center-website#104]
In the right side we have the  user guide (optional) and sidepanel  that is going to be removed

We want to avoid blank right side when there is no user guide

option 1: show description with 100% width when the container of the user guide has been hidden
option 2:  show description with 100% always (remove flex), and thus "user guide" section will always appear below but then adjust  "user guide" section width

**Comment by miranda-company** [comment]
Fixed

**Comment by mcrbsc** [comment]
Perdona Rodolfo creo que no está solucionado lo que te puse en mi último comentario. Echa un vistazo a dust02 y verás que sigue pasando, creo que el commit que hiciste para solucionarlo está bien subido a dust02, es esto no?

.faq-sidepanel .outlined-cta {
  width: 100%;
  padding: 2rem;
}

**Comment by miranda-company** [comment]
Hola Marina!

Si en teoría eso debería resolverlo. 
Mira en [labaula.net](https://www.labaula.net/terrenodepruebas/potus/) y lo verás funcionando. 

Si quieres lo podemos ver juntos.

**Comment by mcrbsc** [comment]
Es que no encuentro ningún caso en la baula...Recuerda que el download user guide ya no lo tenemos en el side panel sino debajo del texto, es por eso que se produce el bug creo

**Comment by miranda-company** [comment]
Mmm el primer FAQ tiene el download button debajo.

**Comment by mcrbsc** [comment]
Ah ya lo veo pero no logro encontrar la diferencia ni en HTML ni en CSS... El contenedor del texto (clase "outlined-cta") tiene las mismas dimensiones en la baula que en dust02 pero el texto y el icono no....

**Comment by miranda-company** [comment]
Marina, he agregado el margin: auto a todas las clases de las font icons.
