### ISSUE TITLE
(FOR THIS WEEK) Tables are not responsive

### ISSUE THREAD

**Issue by mcrbsc** [miranda-company/bsc-dust-regional-center-website#110]
Depending on the size of the table it may not fit into the window, it overflows the window.

I am not able to snapshot it right now but you can see an example in Contacts section of the https://dust02.bsc.es/products/daily-dust-products

there the table overflows if screen is below 625px

**Comment by miranda-company** [comment]
Marina, I'm trying to solve this but it's difficult. 
I'll give it another hour and if I can't find a solution I'll let you know.

**Comment by mcrbsc** [comment]
Ok, I trying to find a solution too. Did you tried installing tablesaw right?

**Comment by miranda-company** [comment]
Yep, I did install tablesaw but couldnt manage to integrate it. It threw a conflicting error.

**Comment by mcrbsc** [comment]
I see that datatables has an extension that would work
https://datatables.net/extensions/responsive/

It adds a collapsible menu to each row that contains the contents of its columns:
https://jsfiddle.net/h8zc1jbx/1/

I have installed it in Plone and I have initialized the table but it is not working as expected. There may be a conflict with your code

**Comment by miranda-company** [comment]
Do you want me to remove the table styles I have applied?
Doing it via JS it´s going to be very hard.

**Comment by mcrbsc** [comment]
In my local environment I do not have the changes that you did to solve this issue. 
But there is still a conflict that makes this plugin not to work. Could we take a look at it together?

**Comment by miranda-company** [comment]
Sure, we can. Can you do it at 6pm?

**Comment by mcrbsc** [comment]
Ok, thanks

**Comment by mcrbsc** [comment]
Como te comentaba por email, el problema es que la tabla no se redimensiona cuando se redimensiona su contenedor padre. No se cómo solucionarlo, debería funcionar con width:100% en la tabla pero no se redimensiona sino que la tabla sobresale del contenedor. Lo puedes ver por ejemplo en https://dust02.bsc.es/products/daily-dust-products

Cómo no puedo dedicar más tiempo a solutionar esto, pensaba ponerle overflow-x:auto al contenedor padre de la tabla pero tampoco funciona en esa tabla que está dentro del menú product-info. Sin embargo "overflow-x:auto" si me funciona en la tabla fake que tengo en mi instalación local. Puedes solucionar esto para que sale el scroll?Gracias!

**Comment by miranda-company** [comment]
Hola Marina, acabo de agregar el overflow auto a .prod-info-panel
¿Esto es lo que querías?

**Comment by mcrbsc** [comment]
Hola Rodolfo, el overflow no hace efecto. Puedes probarlo en la baula?

**Comment by mcrbsc** [comment]
Hola Rodolfo, cuando puedas comentamos esto. Quisiera instalarlo en el update del jueves a las 3

**Comment by miranda-company** [comment]
Hola Marina!
Podría mañana. ¿Te viene bien de quedar a las 4pm?

**Comment by mcrbsc** [comment]
Hola perfecto!

**Comment by mcrbsc** [comment]
Ah perdona, te refieres al miércoles a las 4pm no? También puedo

**Comment by miranda-company** [comment]
Listo Marina, como lo comentamos disminuí el tamaño de la fuente para las tablas cuando el viewport llega al breakpoint 7.

**Comment by miranda-company** [comment]
Hola Marina, encontré una pequeña librería para hacer las tablas responsivas. 
Se llama stacktable.js https://johnpolacek.github.io/stacktable.js/

Por ahora lo he implementado en modal-window-past-events.html 
Para usarlo las tablas tienen que tener la clase de "responsive-table" y para cada página donde se piensen usar tablas habrá que llamar a la función Utils.checkForTables();

Si tienes alguna duda lo hablamos.

**Comment by miranda-company** [comment]
I´m not sure Francesco is using tables in the dashboard, I think so. I´ve only applied some CSS stylings for the dashboard that´s it, you´ll need to ask him. 

I don´t think this will have any effect on the iframe though.

I think applying it globally to the entire site is a good solution but you´ll need to test. 

Let me know if I can help you out with anything.

**Comment by miranda-company** [comment]
Hola!

- I decided to make it smaller below 592 to fit more info without it looking cramped. We can always revert if you want, no prob. 
- I decided to remove the border because this way I think it looks cleaner but let me know if we should add them back in. I couldn't find any example of tables in the prototype. 
- Yes, I think that's correct.

**Comment by mcrbsc** [comment]
Ok! I have already installed it
