### ISSUE TITLE
News slider height does not adapt to content

### ISSUE THREAD

**Issue by mcrbsc** [miranda-company/bsc-dust-regional-center-website#129]
The bug is that the slide can be left out of the slider when the text is long since the text it contains is not limited (in number of lines).

In the screenshot below you can see an example that is happening right now in 320px but this can happen in wider screens depending on the length (in characters) of the news title and news summary. 

You can see that the news date overlaps the website's header:

![FireShot_Capture_788_-_News___WMO_Barcelona_Regional_Center_-_dust02 bsc es](https://user-images.githubusercontent.com/70905912/132373529-ed14561c-71dc-45ac-aa8b-d12d3b4221a5.png)

As the number of characters of these texts (the news title and the news summary) are not truncated by the theme (as we do in the texts displayed inside cards), we could find a worse scenario just if the title would have been a bit longer. See this fake example:

![FireShot_Capture_789_-_News___WMO_Barcelona_Regional_Center_-_dust02 bsc es](https://user-images.githubusercontent.com/70905912/132373540-4315c9a5-6d42-4801-8642-4c2e4b286826.png)

**Comment by mcrbsc** [comment]
@miranda-company  Hola Rodolfo, has podido solucionar esto o quieres que lo hablemos?

**Comment by miranda-company** [comment]
¡Hola Marina!
No he tenido tiempo de verlo. Estamos atendiendo otros proyectos esta semana pero espero poder tener tiempo hacia principios de la siguiente.

**Comment by mcrbsc** [comment]
Hola, he descrito mejor la issue y he preguntado a Diana a ver cómo lo quiere solucionar. Te comento en cuanto sepa o le preguntas a ella ok?

**Comment by miranda-company** [comment]
Vale, gracias por la descripción. 
En cuanto sepan como lo quieren solucionar lo revisamos juntos.

**Comment by mcrbsc** [comment]
Hola, Diana me comenta que simplemente con que adaptes el alto del slide al contenido ya es suficiente porque los editores no van a poner textos super largos. 

Si tu ves otra opción más rápida de implementar nos comentas.

**Comment by miranda-company** [comment]
Hola Marina, buenos días. 

Creo que la mejor opción es limitar los caracteres del título y de la descripción ya que si dejamos que el contenedor responda a cualquier longitud de texto entonces ese div se puede hacer muy largo y el layout de esa pagina se vería mal. 

He implementado esta solución. La verás dentro de el objeto News > Init. 
Los títulos los he limitado a 35 caracteres y a las descripciones a 210. 

Dejame saber si esta solución les viene bien.

**Comment by mcrbsc** [comment]
Hola Rodolfo,

Me parece correcto cortar para que el usuario no pueda poner textos muy largos; sin embargo esto no garantiza un alto máximo....Como ya nos pasaba en las cards.. Si cortaras por lineas si que podrias garantizarlo pero ya sabemos que esto no es fácil de hacer en pantalla responsive... 

Fíjate que esta implementación que has hecho que sólo corta no soluciona el problema que se ve en la captura que puse en la issue, te muestro un screenshot (porque esto aún no está subido en dust02) en el que ni se ven los bullets de navegación a 320px:

![FireShot Capture 793 - News — Plone site - localhost](https://user-images.githubusercontent.com/70905912/133620728-b59c3bf3-ca17-44eb-be67-09298115f2d9.png)


En las cards no hay más remedio que cortar porque el espacio es muy pequeño pero aquí no es tan pequeño y además, como dijo Diana, no pasa nada si el banner crece en alto.

Podrías implementar que el banner se adapte al texto?

**Comment by miranda-company** [comment]
Hola Marina!

Hacer este slider responsivo va tomar tiempo, no veo que sea una implementación sencilla.
Si quieren que lo intentemos lo hacemos pero lo tengo que planear dentro de mi calendario.  

Una otra solución es hacer este slider más alto para moviles y tmb poner el límite de texto más bajo, por ej:
Los títulos los he limitado a 25 caracteres y a las descripciones a 140.

Ya me dicen que quieren que hagamos.

**Comment by mcrbsc** [comment]
Entiendo. Supongo que la dificultad es porque tiene una imagen en background y un texto flotante. El mismo problema tengo en otra web pero allí he de mostrar el texto completo por lo que a mi me interesa que lo resuelvas, cuando puedas, así aprendo. 

Como el problema queda temporalmente solucionado reduciendo el límite en número de caractereres, podrías hacerlo cuando tuvieras un hueco, cuánto tiempo te llevaría?

**Comment by miranda-company** [comment]
En realidad no es tan dificil pero mas bien habrá que pensar bien la solución porque como te digo, el layout va estar botando arriba y abajo. No sé si eso lo tienen en mente? Si quieres podemos tener una llamada el Lunes, de paso me enseñas lo que estas tratando de implementar en el otro lado y vemos que soluciones podemos plantear. 

Te viene bien a las 4pm?

**Comment by mcrbsc** [comment]
Hola, vale lo hablamos pero el lunes sólo puedo de 3.30 a 4, te va bien?

**Comment by miranda-company** [comment]
Ah ok, no lo sabía. 

Me viene bien el Lunes las 10am.
Te envío un link ahora.

**Comment by mcrbsc** [comment]
Solo para que no se me olvide que he de comentarte: "The description’s limit and the title's limit should be responsive. Note that in desktop there is a lot of space to display it and we do not want to truncate it."

**Comment by mcrbsc** [comment]
@miranda-company 
Diana está de acuerdo en reducir la fuente del título de 24 a 20, le he dicho que será sólo en pantallas <768px.
La de la descripción no la modificamos porque ya es 16 en mobile.

**Comment by mcrbsc** [comment]
@miranda-company Quiero integrar esto en el update de esta semana que tendría que ser el último... El update será mñn a las 3 pero yo trabajo por la mñn asi que tengo tiempo de integrarlo por la mñn.

**Comment by miranda-company** [comment]
Hola Marina, ya he subido los cambios que acordamos al slider de News. 
Ahora el l'imite de caracteres cambia en cuanto el tamaño de la pantalla es menor al breakpoint 5. 
También reduje el tamaño del texto en el slider en el breakpoint 7. 

Dejame saber si necesitas algo más.

**Comment by mcrbsc** [comment]
Perfecto Rodolfo pero falta no aplicar el trimado si App.winW > App.breakPoint2 o el breakpoint que tu consideres

**Comment by miranda-company** [comment]
Mmm yo se lo dejaría puesto Marina. Solo para prevenir que el usuario pueda ingresar una burrada de texto que vaya provocar que el texto se desborde. Creo que es más limpio y seguro así. ¿Tu que piensas?

**Comment by mcrbsc** [comment]
@miranda-company 

Ok pero el titulo se ve mal porque  siempre aparece cortado. 

Entonces he subido el número de caracteres del título para pantallas grandes sólo porque ahí no hace falta ser tan conservador no? Al haber espacio, si pongo 60 chars para > breakpoint1 (y 50 para para > breakpoint2), los titulos ocupan 1-1,5 lineas y sólo se producirá un salto de linea (o 2 como mucho si justo coincide un palabra larga al hacer el primer salto de linea).

Por otro lado, veo que no has implementado el bucle que aplica  el trimming (variando el número de caracteres diferente) mientras el texto se sale del contenedor

**Comment by miranda-company** [comment]
Vale, pues subir el limite me parece mejor que dejarlo sin. 

¿A qué te refieres con el bucle?
Ahora mismo el límite de caracteres cambia en cuanto la pantalla es más pequeña que el break5.

**Comment by mcrbsc** [comment]
Comentamos que esta implementación sólo reduce el número de casos en que el texto puede sobresalir del contenedor  pero que para garantizar que no sucede podíamos comparar la altura del contenedor de texto (una vez el texto había sido cortado) con la del slide y si es mayor, volver a deshacer el trimado y volverlo a aplicar con unos caracteres menos.

Era así?

Entiendo cómo funciona la implementación que has hecho por lo que puedo implementar yo el bucle si me dices cómo se hace esa comparación.

**Comment by miranda-company** [comment]
Si podríamos hacer eso para estar seguros. 
Creo que no va pasar núnca pero puede ser buena idea ir a lo seguro. 

Como tu quieras. ¿Quieres probar de hacerlo tu? 
Si te apetece te doy guía. 

1. En el evento de window resize hay que obtener el offset height (altura) del contenedor del slider y también el del elemento de título + el de texto de cada item del slider (newslider-item-title y newslider-item-description)
2. Con esos valores puedes hacer la condición y determinar un límite de altura (treshold). 
3. En la condición podrías aplilcar la solución que consideres como por ejemplo, recortar aún más el texto en caractéres o crecer el contenedor padre unos cuantos pixeles. 

Dejame saber si lo haces tu o quieres que lo haga yo.

**Comment by mcrbsc** [comment]
Gracias, lo que quería saber es el código para obtener "el offset height (altura) del contenedor del slider y también el del elemento de título + el de texto de cada item del slider (newslider-item-title y newslider-item-description)"

**Comment by miranda-company** [comment]
Vale, yo lo hago no prob. Todavía no he cerrado las horas de soporte, Francesco todavía tiene que darme el OK sobre unas modificaciones que me pidió sobre los estilos del dasboard.

**Comment by mcrbsc** [comment]
Ok perfecto gracias. Queda pendiente también la tarea para el min.js.

**Comment by miranda-company** [comment]
Me esta llevando un poco mas de lo que pensaba. Estoy en ello ;)

**Comment by miranda-company** [comment]
Listo Marina, ya he integrado la comparación. 
Es una solución un poco redundante porque ya con el ajuste de caracteres es suficiente. 
De cualquier forma ahora estamos escuchando por la altura tanto del  ".newslider-item-container" y comparandolo con la altura de su contenedor padre ".newslider-container". Verás que a esta comparación estoy agregando un teshold ya que hay como 60px de diferencia entre ambos en el límite. 

Si es que algún slide sobrepasa esa altura entonces un trimm acourre. 

Cualquier cosa me dices.

**Comment by mcrbsc** [comment]
@miranda-company 
He conseguido integrarlo pero he tenido que:

    

- Añadir nuevo atributo "itemsWrap" que inicializo con el antiguo valor que tenia el atributo "container". A este elemento le añado los listeners en "Utils.swipedirection", igual que hacías tu antes
- Subir el heightTreshold porque he probado con un caso que da lugar a un titulo de 3 lineas y una descripción de 4 y quedaba la fecha muy pegada al banner del site

**Comment by mcrbsc** [comment]
He hecho más cambios. No puedo hacer commit porque mi main.js es diferente.

Sigo trabajando en esto porque eh visto que la linea 179 `( News.slider.itemsHeight = [];)` hacía que el cóidgo que corta el texto si se sale del contenedor nunca se ejecutara.  

Y ese código ha de cortar los textos progresivamente hasta que quepan (en un bucle reduciendo por ejemplo 20 carácteres en cada intento) en lugar de cortar los textos directamente a un valor concreto (habías puesto 10 y 60 pero además de ser poquísimo no es responsivo)

**Comment by miranda-company** [comment]
OK, entendido. 
Si necesitas algo me dices.

**Comment by mcrbsc** [comment]
Ya lo he solucionado
