### ISSUE TITLE
URGENT: At which breakpoint should I hide the "switch-to-desktop-message-container" of the Dashboard?

### ISSUE THREAD

**Issue by mcrbsc** [miranda-company/bsc-dust-regional-center-website#130]
Now it is done at 1024px

**Comment by miranda-company** [comment]
Hi Marina!
I think that´s ok, or what´s the issue?

**Comment by mcrbsc** [comment]
Hola Rodolfo,

En dust02 verás que he intentado resolver esta issue. He cambiado la implementación para que el mensaje salga  sólo en pantallas menores a 768px porque sino aparece en Ipad, según me han comentado mis compañeros. 

Pero pienso que no está del todo bien porque mirando la pantalla de 768px veo que la barra de tiempo no se ve completa. Esto es porque tu no hiciste una implementación para una pantalla tan pequeña o porque Francesco no ha instal.lado correctamente el çódigo que le diste? 

Gracias,

**Comment by miranda-company** [comment]
Hi Marina!

For the dashboard we only focused on the sidepanel and the timeslider. 
This week Francesco sent me an email he also want to take a look to the other sections of the dashboard. Maybe this new dasbhoard issues have something to do with what you are experiencing. 

I'll take a look to this begining of next week, I'll let you know.

**Comment by mcrbsc** [comment]
Hi Rodolfo, 

I understand but the issue I see refers to the timeslider which is not fully visible in 768px. So, I expected this bug not to appear right now.

Maybe you did not consider 768px screen?

**Comment by miranda-company** [comment]
Ok, I see. 

This is a change of scope which I hadn´t considered. I implemented the solutions based in the breaks we had. 
I´ll take a look to this next week.

**Comment by mcrbsc** [comment]
Bueno no quiero tampoco que haya un malentendido porque yo soy el mensajero :) Me han pedido que se pueda ver en Ipad, he buscado el ancho de Ipad y por eso he puesto 768px. Si ves otra solución más limpia para que se vea en  Ipad adelante.

Pero si lo que pasa es que no te pidieron que se pudiera ver en 768px entonces el problema es otro...

**Comment by miranda-company** [comment]
No para nada pero no sabía hasta esta semana que querían estos cambios es por eso que adapte el estilo al breakpoint que habíamos puesto. 

No se les hace muy pequeño 768px? tendría que ser el Ipad pero en orientación landscape no? o sea 1024px.

**Comment by mcrbsc** [comment]
Pues no se me había ocurrido pensar en la orientación landscape! Ahora entiendo pero si lo volvemos a poner a 1024px, cómo le indicamos al usuario de tablet que en orientación landscape si puede verlo? En el mensaje del overlay debería estar explicado esto. Qué texto pondrías? 

Cambiando este mensaje entonces no haría falta corregir nada del dashboard ok? Voy a consultarle a Diana si está de acuerdo.

Gracias

**Comment by mcrbsc** [comment]
@miranda-company Ok, ella me dijo que está bien dejarlo a 1024px y cambiar el mensaje asi que cierro la issue
gracias
