### ISSUE TITLE
Gulp minify and bundle JS task

### ISSUE THREAD

**Issue by miranda-company** [miranda-company/bsc-dust-regional-center-website#131]
Hola Marina!

I´ve created the Gulp task for bundling and minifying the js files. 
You´ll see that uppon distribution ¨gulp dist¨ the js files are minified and bundled into a single main.min.js file.

**Comment by miranda-company** [comment]
@mcrbsc

**Comment by mcrbsc** [comment]
Hola, estoy tratando de usar tu gulpfile en el dir de mi proyecto porque yo tengo un main.js ligeramente diferente al tuyo ya que mis HTMLs se generan on-the-fly y el único  fichero html que tengo pregenerado en el dir (index.html) no hace imports JS. Todo esto lo gestiona Plone al iniciarse.

No consigo que minifyJS haga nada, leo el dir src de js pero el dir de salida contiene los JS tal cual sin mimificar. 

He modificado la tarea bundleJS así

    return src(path.srcJSfiles)
        .pipe(minifyJs())
        .pipe(dest(path.distJSdir))
`

Y también he probado esto:

`    return src(path.srcJSfiles)
        .pipe(useref())
        .pipe(gulpIf("*.js", minifyJs()))
        .pipe(dest(path.dist))
`

**Comment by miranda-company** [comment]
gulp-useref necesita que le indiques cuáles son los ficheros en los que debe actuar.
En el html donde tengas referenciados los archivos .js tienes que incluir:


... HTML Markup, list of script / link tags.


"<type> can either be js, css, or remove. It’s best to set type to the type of file that you’re trying to concatenate. If you set type to remove, Gulp will remove the entire build block without generating a file. <path> here refers to the target path of the generated file."

Por ejemplo:


    <script src="js/jquery.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script src="js/stacktable.js"></script>
    <script src="js/gsap.min.js"></script>
    <script src="js/main.js"></script>

**Comment by mcrbsc** [comment]
@miranda-company Puedes ayudarme con esto?

**Comment by miranda-company** [comment]
Si, seguro. 
¿Nos llamamos?
Me viene bien cualquier dia excepto mañana que vamos a estar fuera de la oficina. 

Ya me dices algo.

**Comment by mcrbsc** [comment]
Hoy te va bien? Dime hora, estoy hasta la 1 y después de 2 a 5.30 más o menos

**Comment by miranda-company** [comment]
Te parece hoy a las 4:30?

**Comment by mcrbsc** [comment]
Ok, https://meet.jit.si/RodolfoUpdate
